services:
  jakita:
    build: .
    container_name: jakita
    ports:
      - "${PORT:-8099}:80"
    environment:
      - database.default.hostname=db-jakita
      - database.default.database=db-jakita
      - database.default.username=postgres
      - database.default.password=1234567890
      - database.default.DBDriver=Postgre
      - database.default.port=5432
    depends_on:
      - db-jakita

  db-jakita:
    image: postgres
    container_name: db-jakita
    ports:
      - 5433:5432
    volumes:
      - ./db-jakita:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234567890}
      POSTGRES_DB: ${DB_NAME:-db-jakita}
